### ISSUE TITLE
Various tracebacks when removing a clip from the timeline while it is being thumbnailed

### ISSUE THREAD

**Issue by nekohayo** [pitivi/pitivi#116]
Possibly related to issue #82 ...

Insert a clip that has no filmstrip/waveform thumbnails into the timeline, then remove it before it's done thumbnailing. You will get:

```
Traceback (most recent call last):
  File "timeline/previewers.py", line 470, in bus_message_handler
    self._setThumbnail(struct.get_value("stream-time"), struct.get_value("pixbuf"))
  File "timeline/previewers.py", line 399, in _setThumbnail
    self.thumbs[time].set_from_gdkpixbuf_animated(thumbnail)
  File "timeline/previewers.py", line 545, in set_from_gdkpixbuf_animated
    self.set_from_gdkpixbuf(gdkpixbuf)
  File "timeline/previewers.py", line 535, in set_from_gdkpixbuf
    self.props.content.set_data(pixel_data, Cogl.PixelFormat.RGBA_8888,
AttributeError: 'NoneType' object has no attribute 'set_data'
```

It might also be possible to get the following traceback (but I'm not sure how that one happened... maybe because of a fancy filename/URI?):

```
Traceback (most recent call last):
  File "timeline/previewers.py", line 913, in _messageCb
    self._startRendering()
  File "timeline/previewers.py", line 880, in _startRendering
    self._compute_geometry()
  File "timeline/previewers.py", line 839, in _compute_geometry
    real_duration = self.bElement.get_parent().get_asset().get_duration()
AttributeError: 'NoneType' object has no attribute 'get_asset'
```

**Comment by aleb** [comment]
Never seen this and I can't reproduce. Assuming obsolete.
