### ISSUE TITLE
With the GUADEC 2013 project, trying to insert a PNG causes a traceback with keyframes

### ISSUE THREAD

**Issue by nekohayo** [pitivi/pitivi#135]
The annoying thing is that this happens only on the project of this year's guadec talk... (you can grab it from my my desktop computer, in the "/GUADEC 2013 - pitivi/"  folder at the root).

Trying to drag and drop (or insertEnd) the "1.png" asset into this existing timeline gets me this:

```
Traceback (most recent call last):
  File "pitivi/timeline/timeline.py", line 652, in _trackElementAddedCb
    self._addTrackElement(track, bElement)
  File "pitivi/timeline/timeline.py", line 538, in _addTrackElement
    self._addTimelineElement(track, bElement)
  File "pitivi/timeline/timeline.py", line 451, in _addTimelineElement
    element = URISourceElement(bElement, track, self)
  File "pitivi/timeline/elements.py", line 992, in __init__
    TimelineElement.__init__(self, bElement, track, timeline)
  File "pitivi/timeline/elements.py", line 380, in __init__
    self._createMixingKeyframes()
  File "pitivi/timeline/elements.py", line 554, in _createMixingKeyframes
    self.showKeyframes(self.bElement, spec, isDefault=True)
  File "pitivi/timeline/elements.py", line 449, in showKeyframes
    self.updateKeyframes()
  File "pitivi/timeline/elements.py", line 518, in updateKeyframes
    self.drawLines()
  File "pitivi/timeline/elements.py", line 484, in drawLines
    self._createLine(keyframe, lastKeyframe, None)
  File "pitivi/timeline/elements.py", line 580, in _createLine
    sinX = opp / hyp
ZeroDivisionError: float division by zero
ERROR 21:07:45 pipeline             _busMessageCb: error from <__main__.GstVideoTestSrc object at 0x46bda50 (GstVideoTestSrc at 0x5065c00)>: Internal data flow error. (gstbasesrc.c(2865): gst_base_src_loop (): /pitivi+utils+pipeline+Pipeline:pitivi+utils+pipeline+pipeline1/GESTimeline:gestimeline1/GESVideoTrack:gesvideotrack1/GnlComposition:gnlcomposition2/GnlSource:gnlsource7/GstBin:bin7/GstVideoTestSrc:src:
streaming task paused, reason not-linked (-1)) (pitivi/utils/pipeline.py:449)
```

Filed it here instead of in bugzilla because this doesn't necessarily occur reliably with a blank project, I'm not sure what triggers this exactly... Once, simply importing one mov file and one png file into a blank project, it sometimes segfaulted upon insertion of the PNG after the MOV...

**Comment by aleb** [comment]
Obsolete
