### ISSUE TITLE
Dont assume that all ges_elem has get_asset()

### ISSUE THREAD

**Issue by shakaran** [pitivi/pitivi#147]
With master. I get the following traces. I think that it is because some .png assets doesn't get the preview and cannot render the preview for this error:

```
Traceback (most recent call last):
  File "/app/lib/pitivi/python/pitivi/timeline/previewers.py", line 1014, in _startLevelsDiscovery
    self._launchPipeline()
  File "/app/lib/pitivi/python/pitivi/timeline/previewers.py", line 1025, in _launchPipeline
    asset = self.ges_elem.get_parent().get_asset()
AttributeError: 'NoneType' object has no attribute 'get_asset'
Traceback (most recent call last):
  File "/app/lib/pitivi/python/pitivi/timeline/previewers.py", line 1014, in _startLevelsDiscovery
    self._launchPipeline()
  File "/app/lib/pitivi/python/pitivi/timeline/previewers.py", line 1025, in _launchPipeline
    asset = self.ges_elem.get_parent().get_asset()
AttributeError: 'NoneType' object has no attribute 'get_asset'

(pitivi:12): Gtk-WARNING **: Allocating size to GtkBox 0x2ed5120 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Traceback (most recent call last):
  File "/app/lib/pitivi/python/pitivi/timeline/previewers.py", line 900, in _modulateRate
    assert res
AssertionError
```

**Comment by aleb** [comment]
Could you please close the remaining two tasks you filed and recreate them at https://phabricator.freedesktop.org/ and tag them with `Pitivi`? Or shall I?

**Comment by shakaran** [comment]
Done https://phabricator.freedesktop.org/T7625 Closing this
