### ISSUE TITLE
Cancel loading a project that has missing clips fails

### ISSUE THREAD

**Issue by thiblahute** [pitivi/pitivi#23]
Trying to load a xges (new format) project that has missing clips, and cancelling (not choosing a replacement clip) will cause the following and mess up the UI:

    Traceback (most recent call last):
    File "project.py", line 464, in _missingURICb
        return self.emit("missing-uri", project, error, asset)
     File "utils/signal.py", line 214, in emit
        *args, **kwargs)
    File "utils/signal.py", line 189, in emit
        res = cb(*ar, **kw)
    File "mainwindow.py", line 1082, in _projectManagerMissingUriCb
        self.app.projectManager.newBlankProject()
    File "project.py", line 396, in newBlankProject
        self.emit("new-project-created", project)
    File "utils/signal.py", line 214, in emit
        *args, **kwargs)
    File "utils/signal.py", line 189, in emit
        res = cb(*ar, **kw)
    File "timeline/timeline.py", line 1569, in _projectCreatedCb
        self._pipeline.disconnect_by_func(self.positionChangedCb)
    AttributeError: 'NoneType' object has no attribute 'disconnect_by_func'

**Comment by aleb** [comment]
Fixed
